name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate brand tokens
        run: node scripts/generate-tokens.mjs
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Env audit (Nebius/Vercel)
        run: node scripts/nebius-env-audit.mjs
        continue-on-error: true
      - name: Asset contract
        run: node scripts/validate-assets.mjs
      - name: Cost policy
        run: node scripts/policy-check.mjs
        continue-on-error: true
      - name: Nebius ping (connectivity/auth)
        run: node scripts/nebius-ping.mjs
        continue-on-error: true
      - name: Start static server
        run: npx serve -s dist -l 5000 &
      - name: Wait for server
        run: npx wait-on http://localhost:5000
      - name: Lighthouse (collect)
        run: npx lhci collect --url=http://localhost:5000/ --numberOfRuns=1 --settings.preset=desktop
        continue-on-error: true
      - name: Accessibility (pa11y)
        run: npx pa11y-ci http://localhost:5000/
        continue-on-error: true
      - name: Visual validator (stub)
        run: echo "visual-validator gate pending Nebius integration"
      - name: Accessibility check (stub)
        run: echo "a11y checks to be added"
      - name: Performance check (stub)
        run: echo "Lighthouse mobile checks to be added"

