name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Asset contract
        run: node scripts/validate-assets.mjs
      - name: Cost policy
        run: node scripts/policy-check.mjs
      - name: Visual validator (stub)
        run: echo "visual-validator gate pending Nebius integration"
      - name: Accessibility check (stub)
        run: echo "a11y checks to be added"
      - name: Performance check (stub)
        run: echo "Lighthouse mobile checks to be added"

